#  $Date: 2016-07-22 09:54:18 +0200 (vr, 22 jul 2016) $
#  $Author: bmonhemius $
#-----------------------------------------------------------------------------------------------------------------------
#  About: Copyright
#      (c) Metatronics B.V. - All rights reserved.
#      All rights concerning this software and source codes - including copyrights - are owned by and/or licensed
#      to Metatronics B.V. The software nor the source codes may be used, reproduced, copied, modified, distributed,
#      disclosed or published or used without prior written and explicit consent of Metatronics B.V. The user of this
#      software is not permitted to alter or remove any trademark, copyright or any other notice from.
#-----------------------------------------------------------------------------------------------------------------------

# Headers files that will be exported as interfaces
APIS	= 	stm32f4xx.h \
			$(PF_$(PF)_PROCESSOR_SUB_FAMILY).h \
			system_stm32f4xx.h \
			cmsis.h


# Let JUM decide which rules should be used
MODDIR	= ../../../../
TOPDIR  ?= $(MODDIR)
include $(TOPDIR)/Mk/auto.mk


